// ============================================================================
// Poll Templates - Pre-built templates for common use cases
// ALL POLL TYPES ARE FREE - only response limits differ by plan
// 
// UPDATED: Added high-value survey templates at TOP based on search volume:
// - Employee Engagement: 49,500 monthly searches
// - Customer Satisfaction: 33,100 monthly searches  
// - NPS Survey: 8,100 monthly searches
// - Post-Purchase: 9,900 monthly searches
// ============================================================================

export type PollTemplate = {
    id: string;
    name: string;
    description: string;
    category: 'team' | 'events' | 'feedback' | 'fun' | 'hr' | 'education' | 'survey' | 'creators';
    categoryLabel: string;
    pollType: 'multiple' | 'ranked' | 'pairwise' | 'meeting' | 'rating' | 'rsvp' | 'image' | 'survey';
    icon: string;
    gradient: string;
    accentColor: string;
    question: string;
    options: string[];
    suggestedTheme: string;
    settings?: {
        allowMultiple?: boolean;
        hideResults?: boolean;
        anonymousMode?: boolean;
    };
    previewStyle: {
        bgPattern?: 'dots' | 'grid' | 'waves' | 'none' | 'confetti' | 'lines';
    };
    bestFor: string[];
    estimatedTime: string;
    // NEW: For multi-question surveys
    questionCount?: number;
    badge?: string;
    badgeColor?: string;
    featured?: boolean;
};

export const TEMPLATE_CATEGORIES = [
    { id: 'all', label: 'All Templates', icon: '✨' },
    { id: 'survey', label: 'Surveys & Feedback', icon: '📊' },
    { id: 'team', label: 'Team Decisions', icon: '👥' },
    { id: 'events', label: 'Events & Planning', icon: '🎉' },
    { id: 'feedback', label: 'Quick Feedback', icon: '💬' },
    { id: 'hr', label: 'HR & Culture', icon: '🏢' },
    { id: 'education', label: 'Education', icon: '📚' },
    { id: 'creators', label: 'Content Creators', icon: '🎬' },  // ADD THIS
    { id: 'fun', label: 'Fun & Social', icon: '🎮' },
];

export const POLL_TEMPLATES: PollTemplate[] = [
    // =========================================================================
    // HIGH-VALUE SURVEY TEMPLATES (NEW - FIRST based on search volume)
    // =========================================================================
    {
        id: 'employee-engagement',
        name: 'Employee Engagement Survey',
        description: 'Measure team satisfaction, growth opportunities, and workplace culture with anonymous feedback',
        category: 'survey',
        categoryLabel: 'Surveys & Feedback',
        pollType: 'survey',
        icon: '👥',
        gradient: 'from-emerald-500 to-teal-600',
        accentColor: '#059669',
        question: 'How likely are you to recommend this company as a great place to work?',
        options: [
            'Overall satisfaction (NPS scale)',
            'Growth & development opportunities',
            'Work-life balance rating',
            'Manager relationship',
            'Team collaboration',
            'Recognition & appreciation',
            'Communication clarity',
            'Resource availability',
            'Company direction confidence',
            'Open feedback'
        ],
        suggestedTheme: 'minimal',
        settings: { 
            hideResults: true,
            anonymousMode: true  // Auto-enabled for honest feedback
        },
        previewStyle: { bgPattern: 'dots' },
        bestFor: ['HR teams', 'People operations', 'Quarterly check-ins', 'Culture assessment'],
        estimatedTime: '2 min to create',
        questionCount: 10,
        badge: 'Anonymous',
        badgeColor: 'bg-emerald-100 text-emerald-700',
        featured: true,
    },
    {
        id: 'customer-satisfaction',
        name: 'Customer Satisfaction (CSAT)',
        description: 'Measure customer happiness with your product or service using industry-standard metrics',
        category: 'survey',
        categoryLabel: 'Surveys & Feedback',
        pollType: 'survey',
        icon: '⭐',
        gradient: 'from-amber-500 to-orange-500',
        accentColor: '#f59e0b',
        question: 'How satisfied are you with our product/service?',
        options: [
            'Overall satisfaction (1-5)',
            'Net Promoter Score (0-10)',
            'Ease of use rating',
            'Value for money',
            'Support quality',
            'Feature completeness',
            'What could we improve?'
        ],
        suggestedTheme: 'sunset',
        settings: { hideResults: false },
        previewStyle: { bgPattern: 'waves' },
        bestFor: ['Product teams', 'Customer success', 'Support teams', 'Post-purchase'],
        estimatedTime: '2 min to create',
        questionCount: 7,
        badge: 'NPS Included',
        badgeColor: 'bg-amber-100 text-amber-700',
        featured: true,
    },
    {
        id: 'nps-survey',
        name: 'Quick NPS Survey',
        description: 'The industry-standard Net Promoter Score survey - just 2 questions to measure loyalty',
        category: 'survey',
        categoryLabel: 'Surveys & Feedback',
        pollType: 'survey',
        icon: '📈',
        gradient: 'from-cyan-500 to-blue-600',
        accentColor: '#0891b2',
        question: 'How likely are you to recommend us to a friend or colleague?',
        options: [
            'NPS Score (0-10 scale)',
            'What\'s the main reason for your score?'
        ],
        suggestedTheme: 'ocean',
        settings: { hideResults: false },
        previewStyle: { bgPattern: 'waves' },
        bestFor: ['Quick pulse checks', 'Customer loyalty', 'Benchmarking', 'Trend tracking'],
        estimatedTime: '30 sec to create',
        questionCount: 2,
        badge: 'Quick',
        badgeColor: 'bg-cyan-100 text-cyan-700',
        featured: true,
    },
    {
        id: 'post-purchase-feedback',
        name: 'Post-Purchase Feedback',
        description: 'Understand the buying experience and gather insights for improvement',
        category: 'survey',
        categoryLabel: 'Surveys & Feedback',
        pollType: 'survey',
        icon: '🛒',
        gradient: 'from-violet-500 to-purple-600',
        accentColor: '#7c3aed',
        question: 'How was your purchase experience?',
        options: [
            'Overall purchase satisfaction',
            'How did you hear about us?',
            'Was checkout easy?',
            'Any suggestions for improvement?'
        ],
        suggestedTheme: 'minimal',
        settings: { hideResults: false },
        previewStyle: { bgPattern: 'dots' },
        bestFor: ['E-commerce', 'Retail', 'Service businesses', 'Sales teams'],
        estimatedTime: '1 min to create',
        questionCount: 4,
    },
    {
        id: 'event-feedback',
        name: 'Event Feedback Survey',
        description: 'Gather attendee feedback to improve future events',
        category: 'survey',
        categoryLabel: 'Surveys & Feedback',
        pollType: 'survey',
        icon: '🎤',
        gradient: 'from-rose-500 to-pink-600',
        accentColor: '#e11d48',
        question: 'How would you rate this event overall?',
        options: [
            'Overall event rating (1-5 stars)',
            'Speaker/content quality',
            'Venue & logistics',
            'Networking opportunities',
            'Would you attend again?',
            'What could be improved?'
        ],
        suggestedTheme: 'sunset',
        settings: { hideResults: false },
        previewStyle: { bgPattern: 'confetti' },
        bestFor: ['Conferences', 'Workshops', 'Webinars', 'Training sessions'],
        estimatedTime: '2 min to create',
        questionCount: 6,
    },
    {
        id: 'team-feedback',
        name: 'Team Feedback Survey',
        description: 'Collect anonymous feedback from your team on projects, processes, or ideas',
        category: 'survey',
        categoryLabel: 'Surveys & Feedback',
        pollType: 'survey',
        icon: '💬',
        gradient: 'from-blue-500 to-indigo-600',
        accentColor: '#3b82f6',
        question: 'How do you feel about our current team processes?',
        options: [
            'Process efficiency rating',
            'Communication clarity',
            'Workload balance',
            'What\'s working well?',
            'What needs improvement?'
        ],
        suggestedTheme: 'minimal',
        settings: { 
            hideResults: true,
            anonymousMode: true
        },
        previewStyle: { bgPattern: 'grid' },
        bestFor: ['Team retrospectives', 'Process improvement', 'Manager feedback', 'Sprint reviews'],
        estimatedTime: '1 min to create',
        questionCount: 5,
        badge: 'Anonymous',
        badgeColor: 'bg-blue-100 text-blue-700',
    },

    // =========================================================================
    // QUICK FEEDBACK - Single-question polls for instant feedback
    // These are TRUE single-question polls (not multi-question surveys)
    // =========================================================================
    {
        id: 'quick-nps',
        name: 'Quick NPS',
        description: 'Single-question Net Promoter Score - the industry standard for measuring loyalty',
        category: 'feedback',
        categoryLabel: 'Quick Feedback',
        pollType: 'rating',
        icon: '📊',
        gradient: 'from-cyan-500 to-blue-600',
        accentColor: '#0891b2',
        question: 'How likely are you to recommend us to a friend or colleague?',
        options: ['Rate 0-10'],
        suggestedTheme: 'ocean',
        settings: { hideResults: false },
        previewStyle: { bgPattern: 'waves' },
        bestFor: ['Customer feedback', 'Quick pulse checks', 'NPS tracking'],
        estimatedTime: '15 sec to create',
        badge: 'Quick',
        badgeColor: 'bg-cyan-100 text-cyan-700',
    },
    {
        id: 'quick-csat',
        name: 'Quick CSAT',
        description: 'Simple 5-star satisfaction rating - get instant feedback on any experience',
        category: 'feedback',
        categoryLabel: 'Quick Feedback',
        pollType: 'rating',
        icon: '⭐',
        gradient: 'from-amber-500 to-orange-500',
        accentColor: '#f59e0b',
        question: 'How satisfied are you with your experience?',
        options: ['Rate 1-5 stars'],
        suggestedTheme: 'sunset',
        settings: { hideResults: false },
        previewStyle: { bgPattern: 'dots' },
        bestFor: ['Customer satisfaction', 'Service feedback', 'Product ratings'],
        estimatedTime: '15 sec to create',
        badge: 'Quick',
        badgeColor: 'bg-amber-100 text-amber-700',
    },
    {
        id: 'quick-thumbs',
        name: 'Thumbs Up / Down',
        description: 'The simplest feedback - just yes or no. Perfect for quick decisions.',
        category: 'feedback',
        categoryLabel: 'Quick Feedback',
        pollType: 'multiple',
        icon: '👍',
        gradient: 'from-emerald-500 to-teal-500',
        accentColor: '#10b981',
        question: 'Was this helpful?',
        options: ['👍 Yes', '👎 No'],
        suggestedTheme: 'forest',
        settings: { allowMultiple: false },
        previewStyle: { bgPattern: 'none' },
        bestFor: ['Content feedback', 'Quick reactions', 'Binary decisions'],
        estimatedTime: '10 sec to create',
        badge: 'Quick',
        badgeColor: 'bg-emerald-100 text-emerald-700',
    },
    {
        id: 'quick-emoji',
        name: 'Emoji Reaction',
        description: 'Fun emoji-based feedback - great for mood checks and quick surveys',
        category: 'feedback',
        categoryLabel: 'Quick Feedback',
        pollType: 'multiple',
        icon: '😀',
        gradient: 'from-pink-500 to-rose-500',
        accentColor: '#ec4899',
        question: 'How are you feeling today?',
        options: ['😀 Great', '🙂 Good', '😐 Okay', '😕 Not great', '😢 Bad'],
        suggestedTheme: 'neon',
        settings: { allowMultiple: false },
        previewStyle: { bgPattern: 'confetti' },
        bestFor: ['Team mood checks', 'Quick reactions', 'Fun feedback'],
        estimatedTime: '15 sec to create',
        badge: 'Quick',
        badgeColor: 'bg-pink-100 text-pink-700',
    },
    {
        id: 'quick-effort',
        name: 'Customer Effort Score',
        description: 'Measure how easy it was to complete a task or get help',
        category: 'feedback',
        categoryLabel: 'Quick Feedback',
        pollType: 'rating',
        icon: '🎯',
        gradient: 'from-violet-500 to-purple-600',
        accentColor: '#8b5cf6',
        question: 'How easy was it to complete your task today?',
        options: ['Rate 1-5'],
        suggestedTheme: 'minimal',
        settings: { hideResults: false },
        previewStyle: { bgPattern: 'dots' },
        bestFor: ['UX feedback', 'Support feedback', 'Process improvement'],
        estimatedTime: '15 sec to create',
        badge: 'Quick',
        badgeColor: 'bg-violet-100 text-violet-700',
    },
{
    id: 'client-satisfaction-survey',
    name: 'Client Satisfaction Survey',
    description: 'Delivery quality, communication, expertise, value, and renewal intent for agencies, consultants, and freelancers.',
    category: 'survey',
    categoryLabel: 'Surveys & Feedback',
    pollType: 'survey',
    icon: '🤝',
    gradient: 'from-amber-600 to-yellow-600',
    accentColor: '#d97706',
    question: 'How satisfied are you with the quality of work we have delivered for you?',
    options: ['Delivery quality', 'Communication', 'Expertise', 'Responsiveness', 'Value for money', 'Renewal intent', 'NPS', 'Open feedback'],
    suggestedTheme: 'minimal',
    settings: { anonymousMode: false },
    previewStyle: { bgPattern: 'grid' },
    bestFor: ['Agencies', 'Consultants', 'Freelancers'],
    estimatedTime: '3-4 min',
    questionCount: 9,
},
{
    id: 'personal-trainer-feedback-survey',
    name: 'Personal Trainer Feedback Survey',
    description: 'Session quality, programme progression, motivation, goal clarity, and referral intent for PTs and fitness coaches.',
    category: 'survey',
    categoryLabel: 'Surveys & Feedback',
    pollType: 'survey',
    icon: '💪',
    gradient: 'from-orange-500 to-red-500',
    accentColor: '#ea580c',
    question: 'How well do you feel your programme is progressing toward your goals?',
    options: ['Session quality', 'Programme design', 'Motivation', 'Progression', 'Goal clarity', 'Between-session support', 'Value', 'NPS', 'Open feedback'],
    suggestedTheme: 'sunset',
    settings: { anonymousMode: false },
    previewStyle: { bgPattern: 'dots' },
    bestFor: ['Personal Trainers', 'Fitness Coaches', 'Online Coaches'],
    estimatedTime: '2-3 min',
    questionCount: 9,
},
{
    id: 'coworking-space-survey',
    name: 'Coworking Space Member Survey',
    description: 'Internet reliability, community value, events, amenities, and renewal intent for coworking operators.',
    category: 'survey',
    categoryLabel: 'Surveys & Feedback',
    pollType: 'survey',
    icon: '🏢',
    gradient: 'from-indigo-500 to-violet-600',
    accentColor: '#4f46e5',
    question: 'How valuable is the sense of community and networking at this space?',
    options: ['Overall satisfaction', 'Internet reliability', 'Community value', 'Events', 'Staff', 'Amenities', 'Value for money', 'Renewal intent', 'Open feedback'],
    suggestedTheme: 'minimal',
    settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'grid' },
    bestFor: ['Coworking Spaces', 'Shared Offices', 'Business Centres'],
    estimatedTime: '2-3 min',
    questionCount: 9,
},
{
    id: 'candidate-experience-survey',
    name: 'Candidate Experience Survey',
    description: 'Application clarity, interview quality, perceived fairness, and employer brand for HR and talent teams.',
    category: 'hr',
    categoryLabel: 'HR & Culture',
    pollType: 'survey',
    icon: '🎯',
    gradient: 'from-sky-500 to-blue-600',
    accentColor: '#0284c7',
    question: 'How fair and objective did the assessment and interview process feel?',
    options: ['Job description clarity', 'Application ease', 'Recruiter communication', 'Interview quality', 'Perceived fairness', 'Decision speed', 'Employer brand', 'NPS', 'Open feedback'],
    suggestedTheme: 'minimal',
    settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'dots' },
    bestFor: ['HR Teams', 'Talent Acquisition', 'Employer Brand'],
    estimatedTime: '2-3 min',
    questionCount: 9,
    badge: 'Anonymous',
    badgeColor: 'bg-sky-100 text-sky-700',
},
{
    id: 'team-building-survey',
    name: 'Team Building Event Survey',
    description: 'Activity enjoyment, team connection, inclusion, facilitation quality, and budget value for HR teams.',
    category: 'hr',
    categoryLabel: 'HR & Culture',
    pollType: 'survey',
    icon: '🌿',
    gradient: 'from-emerald-500 to-teal-600',
    accentColor: '#059669',
    question: 'How inclusive and accessible was the activity for all team members?',
    options: ['Enjoyment', 'Team connection', 'Inclusion', 'Facilitation', 'Logistics', 'Budget value', 'Repeat interest', 'NPS', 'Open feedback'],
    suggestedTheme: 'forest',
    settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'waves' },
    bestFor: ['HR Teams', 'People Managers', 'Team Leads'],
    estimatedTime: '2-3 min',
    questionCount: 9,
    badge: 'Anonymous',
    badgeColor: 'bg-emerald-100 text-emerald-700',
},
{
    id: 'childcare-parent-survey',
    name: 'Childcare Parent Survey',
    description: 'Child safety, staff warmth, key person bond, settling-in, and communication for nurseries and daycares.',
    category: 'education',
    categoryLabel: 'Education',
    pollType: 'survey',
    icon: '🌟',
    gradient: 'from-sky-400 to-blue-500',
    accentColor: '#0369a1',
    question: 'How safe and well cared for does your child feel in our setting?',
    options: ['Overall satisfaction', 'Child safety', 'Staff warmth', 'Settling-in', 'Learning activities', 'Communication', 'Meals', 'NPS', 'Open feedback'],
    suggestedTheme: 'ocean',
    settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'dots' },
    bestFor: ['Nurseries', 'Daycares', 'Childminders'],
    estimatedTime: '2-3 min',
    questionCount: 9,
},
{
    id: 'online-course-feedback-survey',
    name: 'Online Course Feedback Survey',
    description: 'Content quality, instructor style, pacing, learning outcomes, and platform experience for course creators.',
    category: 'education',
    categoryLabel: 'Education',
    pollType: 'survey',
    icon: '🎓',
    gradient: 'from-lime-500 to-green-600',
    accentColor: '#65a30d',
    question: 'How well did the course help you achieve the learning objectives it promised?',
    options: ['Overall satisfaction', 'Content quality', 'Instructor style', 'Pacing', 'Platform experience', 'Learning objectives met', 'Value', 'NPS', 'Open feedback'],
    suggestedTheme: 'forest',
    settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'grid' },
    bestFor: ['Course Creators', 'EdTech Platforms', 'L&D Teams'],
    estimatedTime: '2-3 min',
    questionCount: 9,
},

// ── CUSTOMER (missing) ────────────────────────────────────────────
{
    id: 'restaurant-feedback',
    name: 'Restaurant Feedback Survey',
    description: 'Food quality, service, atmosphere, value, and return visit intent.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '🍽️', gradient: 'from-orange-500 to-red-500', accentColor: '#ea580c',
    question: 'How would you rate your overall experience today?',
    options: ['Food quality', 'Service', 'Atmosphere', 'Value', 'Return intent', 'Open feedback'],
    suggestedTheme: 'sunset', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'waves' }, bestFor: ['Restaurants', 'Cafes', 'Food businesses'],
    estimatedTime: '2 min', questionCount: 8,
},
{
    id: 'customer-churn',
    name: 'Customer Churn Survey',
    description: 'Know exactly why customers cancel at the only moment they will tell you.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '📉', gradient: 'from-red-500 to-rose-600', accentColor: '#dc2626',
    question: 'What is the primary reason you are cancelling today?',
    options: ['Cancellation reason', 'Satisfaction before leaving', 'What failed', 'What you will use instead', 'Win-back interest', 'NPS', 'Final feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: false },
    previewStyle: { bgPattern: 'grid' }, bestFor: ['SaaS', 'Subscriptions', 'Retention teams'],
    estimatedTime: '3 min', questionCount: 8,
},
{
    id: 'sales-feedback',
    name: 'Sales Process Feedback Survey',
    description: 'Know exactly why deals close and why they do not — for won and lost deals.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '📊', gradient: 'from-orange-500 to-amber-500', accentColor: '#f59e0b',
    question: 'How would you rate your overall experience with our sales team?',
    options: ['Sales experience', 'Responsiveness', 'Understanding of needs', 'Proposal quality', 'Pricing clarity', 'Trust built', 'Competitive comparison', 'Outcome', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: false },
    previewStyle: { bgPattern: 'dots' }, bestFor: ['B2B Sales', 'Account managers', 'Revenue teams'],
    estimatedTime: '3 min', questionCount: 9,
},
{
    id: 'real-estate-agent',
    name: 'Real Estate Agent Feedback Survey',
    description: 'Know how your agents perform before clients post elsewhere.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '🏡', gradient: 'from-yellow-500 to-amber-600', accentColor: '#d97706',
    question: 'How well did your agent keep you updated throughout the process?',
    options: ['Communication', 'Market knowledge', 'Listening', 'Viewings quality', 'Negotiation', 'Transparency', 'Legal guidance', 'NPS', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: false },
    previewStyle: { bgPattern: 'grid' }, bestFor: ['Estate agents', 'Property agencies', 'Brokers'],
    estimatedTime: '3 min', questionCount: 9,
},
{
    id: 'insurance-satisfaction',
    name: 'Insurance Customer Satisfaction Survey',
    description: 'Know what policyholders think before they renew elsewhere.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '🛡️', gradient: 'from-blue-600 to-indigo-700', accentColor: '#2563eb',
    question: 'How clearly were your policy terms and coverage explained to you?',
    options: ['Policy clarity', 'Claims process', 'Claims communication', 'Claims speed', 'Premium fairness', 'Renewal ease', 'Overall satisfaction', 'NPS', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: false },
    previewStyle: { bgPattern: 'grid' }, bestFor: ['Insurance providers', 'Brokers', 'Claims teams'],
    estimatedTime: '3 min', questionCount: 9,
},
{
    id: 'spa-wellness-feedback',
    name: 'Spa and Wellness Feedback Survey',
    description: 'Treatment quality, therapist professionalism, ambiance, and rebooking intent.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '🌿', gradient: 'from-emerald-500 to-teal-600', accentColor: '#059669',
    question: 'Overall, how satisfied are you with your visit today?',
    options: ['Overall satisfaction', 'Treatment quality', 'Therapist professionalism', 'Cleanliness and ambiance', 'Welcome experience', 'Treatment match', 'Value for money', 'NPS', 'Open feedback'],
    suggestedTheme: 'forest', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'waves' }, bestFor: ['Spas', 'Wellness centres', 'Beauty therapists'],
    estimatedTime: '2 min', questionCount: 9,
},
{
    id: 'food-delivery-survey',
    name: 'Food Delivery Feedback Survey',
    description: 'Order accuracy, delivery time, food quality, and driver experience.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '🛵', gradient: 'from-orange-400 to-red-500', accentColor: '#f97316',
    question: 'How satisfied are you with the delivery time for your order?',
    options: ['Delivery time', 'Order accuracy', 'Driver conduct', 'Food quality', 'Packaging', 'Value for money', 'Reorder intent', 'Open feedback'],
    suggestedTheme: 'sunset', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'dots' }, bestFor: ['Food delivery', 'Restaurants', 'Dark kitchens'],
    estimatedTime: '2 min', questionCount: 8,
},
{
    id: 'gym-fitness-class-survey',
    name: 'Gym and Fitness Class Survey',
    description: 'Class quality, instructor performance, facilities, and membership satisfaction.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '🏋️', gradient: 'from-violet-500 to-purple-600', accentColor: '#7c3aed',
    question: 'How would you rate the overall quality of the class or session?',
    options: ['Class quality', 'Instructor knowledge', 'Pacing and structure', 'Cleanliness', 'Equipment quality', 'Atmosphere', 'Membership value', 'NPS', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'dots' }, bestFor: ['Gyms', 'Fitness studios', 'PT instructors'],
    estimatedTime: '2 min', questionCount: 9,
},
{
    id: 'retail-customer-survey',
    name: 'Retail Customer Survey',
    description: 'Shopping experience, staff, checkout, atmosphere, value, and NPS. QR code friendly.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '🛍️', gradient: 'from-pink-500 to-rose-500', accentColor: '#e11d48',
    question: 'How would you rate your overall shopping experience today?',
    options: ['Overall experience', 'Product range', 'Findability', 'Staff helpfulness', 'Checkout experience', 'Store atmosphere', 'Value for money', 'NPS', 'Open feedback'],
    suggestedTheme: 'sunset', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'waves' }, bestFor: ['Retail stores', 'Ecommerce', 'Pop-ups'],
    estimatedTime: '2 min', questionCount: 9,
},
{
    id: 'subscription-service-survey',
    name: 'Subscription Service Survey',
    description: 'Satisfaction, value, feature quality, support, and churn risk before renewal.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '🔁', gradient: 'from-violet-600 to-indigo-700', accentColor: '#6d28d9',
    question: 'Overall, how satisfied are you with our product or service?',
    options: ['Overall satisfaction', 'Value for money', 'Feature satisfaction', 'Onboarding ease', 'Support quality', 'Ease of use', 'Renewal intent', 'NPS', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: false },
    previewStyle: { bgPattern: 'grid' }, bestFor: ['SaaS', 'Subscription boxes', 'Membership services'],
    estimatedTime: '3 min', questionCount: 9,
    badge: 'Churn Signal', badgeColor: 'bg-violet-100 text-violet-700',
},

// ── EDUCATION (missing) ───────────────────────────────────────────
{
    id: 'course-feedback',
    name: 'Course Evaluation Survey',
    description: 'Content quality, delivery, pacing, learning materials, and student outcomes.',
    category: 'education', categoryLabel: 'Education', pollType: 'survey',
    icon: '📋', gradient: 'from-blue-500 to-indigo-600', accentColor: '#3b82f6',
    question: 'How would you rate the overall quality of this course?',
    options: ['Overall quality', 'Content quality', 'Instructor delivery', 'Pacing', 'Materials', 'Learning outcomes', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'grid' }, bestFor: ['Universities', 'Training providers', 'Educators'],
    estimatedTime: '2 min', questionCount: 9,
},
{
    id: 'training-feedback',
    name: 'Training Feedback Survey',
    description: 'Post-training effectiveness, delivery format, and learning transfer.',
    category: 'education', categoryLabel: 'Education', pollType: 'survey',
    icon: '📚', gradient: 'from-teal-500 to-cyan-600', accentColor: '#0891b2',
    question: 'How would you rate the overall quality of this training session?',
    options: ['Overall quality', 'Trainer knowledge', 'Relevance to job', 'Pacing', 'Format preference', 'Confidence to apply', 'Employer recommendation', 'Open feedback'],
    suggestedTheme: 'ocean', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'waves' }, bestFor: ['L&D teams', 'Corporate training', 'HR departments'],
    estimatedTime: '2 min', questionCount: 8,
},
{
    id: 'student-satisfaction',
    name: 'Student Satisfaction Survey',
    description: 'Academic quality, support services, campus experience, and NPS.',
    category: 'education', categoryLabel: 'Education', pollType: 'survey',
    icon: '🎒', gradient: 'from-indigo-500 to-purple-600', accentColor: '#6366f1',
    question: 'How satisfied are you with the academic quality of your programme?',
    options: ['Academic quality', 'Teaching quality', 'Assessment feedback', 'Academic support', 'Student services', 'Campus or online experience', 'Value for fees', 'NPS', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'dots' }, bestFor: ['Universities', 'Colleges', 'Higher education'],
    estimatedTime: '3 min', questionCount: 9,
},
{
    id: 'school-satisfaction',
    name: 'School Satisfaction Survey',
    description: 'Teaching quality, communication, pastoral care, leadership, and parent NPS.',
    category: 'education', categoryLabel: 'Education', pollType: 'survey',
    icon: '🏫', gradient: 'from-sky-500 to-blue-600', accentColor: '#0284c7',
    question: 'How satisfied are you with the academic standards at this school?',
    options: ['Academic standards', 'Teaching quality', 'Student support', 'Parent communication', 'Pastoral care', 'Extracurricular activities', 'Leadership vision', 'Value for fees', 'NPS', 'Open feedback'],
    suggestedTheme: 'ocean', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'dots' }, bestFor: ['Schools', 'Independent schools', 'MATs'],
    estimatedTime: '3 min', questionCount: 10,
},
{
    id: 'alumni-survey',
    name: 'Alumni Survey',
    description: 'Education value, career outcomes, alumni connection, and advocacy.',
    category: 'education', categoryLabel: 'Education', pollType: 'survey',
    icon: '🎓', gradient: 'from-amber-500 to-orange-600', accentColor: '#d97706',
    question: 'How well did your education prepare you for your career?',
    options: ['Career preparation', 'Skills developed', 'Career outcomes', 'Employer recognition', 'Alumni connection value', 'Engagement interest', 'Giving interest', 'NPS', 'Open feedback'],
    suggestedTheme: 'sunset', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'grid' }, bestFor: ['Universities', 'Business schools', 'Alumni relations teams'],
    estimatedTime: '3 min', questionCount: 9,
},
{
    id: 'school-parent-survey',
    name: 'School Parent Survey',
    description: 'Academic quality, communication, pastoral support, and parent NPS.',
    category: 'education', categoryLabel: 'Education', pollType: 'survey',
    icon: '👨‍👩‍👧', gradient: 'from-emerald-500 to-teal-600', accentColor: '#059669',
    question: 'How satisfied are you with your child\'s progress and development at this school?',
    options: ['Child progress', 'Teaching quality', 'Parent communication', 'Parent involvement', 'Pastoral support', 'SEN support', 'Value for fees', 'NPS', 'Open feedback'],
    suggestedTheme: 'forest', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'waves' }, bestFor: ['Schools', 'Academies', 'Independent schools'],
    estimatedTime: '3 min', questionCount: 9,
},

// ── EMPLOYEE / HR (missing) ───────────────────────────────────────
{
    id: 'employee-satisfaction',
    name: 'Employee Satisfaction Survey',
    description: 'Role satisfaction, team dynamics, manager relationship, and retention intent.',
    category: 'hr', categoryLabel: 'HR & Culture', pollType: 'survey',
    icon: '😊', gradient: 'from-green-500 to-emerald-600', accentColor: '#16a34a',
    question: 'How satisfied are you with your role and responsibilities?',
    options: ['Role satisfaction', 'Workload balance', 'Skills utilisation', 'Team dynamics', 'Manager relationship', 'Recognition', 'Retention intent', 'Open feedback'],
    suggestedTheme: 'forest', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'dots' }, bestFor: ['HR teams', 'People ops', 'Annual reviews'],
    estimatedTime: '3 min', questionCount: 8,
    badge: 'Anonymous', badgeColor: 'bg-green-100 text-green-700',
},
{
    id: 'exit-interview',
    name: 'Exit Interview Survey',
    description: 'Why people leave, experience quality, and honest offboarding feedback.',
    category: 'hr', categoryLabel: 'HR & Culture', pollType: 'survey',
    icon: '🚪', gradient: 'from-slate-500 to-gray-600', accentColor: '#475569',
    question: 'What is the primary reason you are leaving?',
    options: ['Leaving reason', 'Decision timing', 'Satisfaction before leaving', 'Manager relationship', 'Culture fit', 'Growth opportunities', 'Would return', 'Recommend as employer', 'Final feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'grid' }, bestFor: ['HR teams', 'People ops', 'Offboarding'],
    estimatedTime: '3 min', questionCount: 10,
    badge: 'Anonymous', badgeColor: 'bg-slate-100 text-slate-700',
},
{
    id: 'weekly-pulse',
    name: 'Weekly Pulse Survey',
    description: 'Fast 5-question anonymous check-in on team mood, workload, and support.',
    category: 'hr', categoryLabel: 'HR & Culture', pollType: 'survey',
    icon: '💓', gradient: 'from-rose-400 to-pink-500', accentColor: '#f43f5e',
    question: 'How are you feeling about work this week?',
    options: ['Mood this week', 'Workload', 'Support needed', 'Blocker', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'dots' }, bestFor: ['Team leads', 'Managers', 'Weekly rituals'],
    estimatedTime: '1 min', questionCount: 5,
    badge: 'Quick', badgeColor: 'bg-rose-100 text-rose-700',
},
{
    id: '360-feedback',
    name: '360 Degree Feedback Survey',
    description: 'Communication, collaboration, reliability, and development feedback from peers.',
    category: 'hr', categoryLabel: 'HR & Culture', pollType: 'survey',
    icon: '🔄', gradient: 'from-violet-500 to-purple-600', accentColor: '#7c3aed',
    question: 'How effectively does this person communicate with their team?',
    options: ['Communication', 'Reliability', 'Collaboration', 'Problem solving', 'Top strengths', 'Development areas', 'Growth areas to work on', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'grid' }, bestFor: ['Performance reviews', 'Leadership development', 'HR teams'],
    estimatedTime: '3 min', questionCount: 10,
    badge: 'Anonymous', badgeColor: 'bg-violet-100 text-violet-700',
},
{
    id: 'employee-benefits',
    name: 'Employee Benefits Survey',
    description: 'Benefits awareness, satisfaction by category, and priority preferences.',
    category: 'hr', categoryLabel: 'HR & Culture', pollType: 'survey',
    icon: '🎁', gradient: 'from-sky-500 to-blue-600', accentColor: '#0284c7',
    question: 'How satisfied are you with your current benefits package overall?',
    options: ['Benefits awareness', 'Overall satisfaction', 'Healthcare', 'Flexibility', 'L&D', 'Financial benefits', 'Wellbeing', 'Priority ranking', 'Missing benefits', 'Open feedback'],
    suggestedTheme: 'ocean', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'waves' }, bestFor: ['HR teams', 'Reward and benefits', 'People ops'],
    estimatedTime: '3 min', questionCount: 10,
},
{
    id: 'remote-work',
    name: 'Remote Work Survey',
    description: 'Home setup, productivity, collaboration, isolation, and hybrid preferences.',
    category: 'hr', categoryLabel: 'HR & Culture', pollType: 'survey',
    icon: '🏠', gradient: 'from-teal-500 to-emerald-600', accentColor: '#14b8a6',
    question: 'How would you rate your home working environment and setup?',
    options: ['Home setup', 'Setup support needs', 'Productivity vs office', 'Communication tools', 'Collaboration quality', 'Isolation feeling', 'Manager visibility', 'Hybrid preference', 'Policy improvements', 'Open feedback'],
    suggestedTheme: 'forest', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'dots' }, bestFor: ['Remote teams', 'Hybrid policy planning', 'People ops'],
    estimatedTime: '3 min', questionCount: 10,
},
{
    id: 'job-satisfaction',
    name: 'Job Satisfaction Survey',
    description: 'Role fit, growth, culture, compensation, and retention intent.',
    category: 'hr', categoryLabel: 'HR & Culture', pollType: 'survey',
    icon: '⚡', gradient: 'from-amber-500 to-yellow-500', accentColor: '#f59e0b',
    question: 'How satisfied are you with your current role and responsibilities?',
    options: ['Role satisfaction', 'Autonomy', 'Workload', 'Growth opportunities', 'Manager quality', 'Team culture', 'Compensation fairness', 'Values alignment', 'Retention intent', 'Open feedback'],
    suggestedTheme: 'sunset', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'waves' }, bestFor: ['HR teams', 'People ops', 'Mid-year reviews'],
    estimatedTime: '3 min', questionCount: 10,
    badge: 'Anonymous', badgeColor: 'bg-amber-100 text-amber-700',
},
{
    id: 'diversity-inclusion',
    name: 'Diversity and Inclusion Survey',
    description: 'Belonging, psychological safety, inclusive leadership, and equity perception.',
    category: 'hr', categoryLabel: 'HR & Culture', pollType: 'survey',
    icon: '🤝', gradient: 'from-fuchsia-500 to-purple-600', accentColor: '#a855f7',
    question: 'How strongly do you feel a sense of belonging at this organisation?',
    options: ['Belonging', 'Respectful treatment', 'Inclusive leadership', 'Bias in decisions', 'Psychological safety', 'Equity in opportunities', 'Comfortable being yourself', 'Speaking up safety', 'Inclusion vs last year', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'dots' }, bestFor: ['DEI teams', 'HR', 'People ops', 'Leadership'],
    estimatedTime: '3 min', questionCount: 10,
    badge: 'Anonymous', badgeColor: 'bg-fuchsia-100 text-fuchsia-700',
},
{
    id: 'employee-wellbeing',
    name: 'Employee Wellbeing Survey',
    description: 'Energy levels, stress, connection, manager support, and overall health at work.',
    category: 'hr', categoryLabel: 'HR & Culture', pollType: 'survey',
    icon: '🌱', gradient: 'from-green-400 to-emerald-500', accentColor: '#22c55e',
    question: 'How would you rate your current energy and motivation levels at work?',
    options: ['Energy and motivation', 'Stress levels', 'Workload manageability', 'Connection to colleagues', 'Manager support', 'Psychological safety', 'Sleep and recovery', 'Resources available', 'Wellbeing vs last year', 'Open feedback'],
    suggestedTheme: 'forest', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'waves' }, bestFor: ['HR', 'People ops', 'Wellbeing programmes'],
    estimatedTime: '3 min', questionCount: 10,
    badge: 'Anonymous', badgeColor: 'bg-green-100 text-green-700',
},
{
    id: 'internship-feedback',
    name: 'Internship Feedback Survey',
    description: 'Learning quality, project work, culture, and full-time conversion intent.',
    category: 'hr', categoryLabel: 'HR & Culture', pollType: 'survey',
    icon: '🌟', gradient: 'from-sky-400 to-indigo-500', accentColor: '#6366f1',
    question: 'How satisfied are you with the learning and development opportunities during your internship?',
    options: ['Learning quality', 'Project relevance', 'Skills development', 'Culture and values', 'Manager support', 'Team inclusion', 'Career development clarity', 'Full-time interest', 'Would recommend', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'dots' }, bestFor: ['Graduate recruitment', 'Early careers', 'HR teams'],
    estimatedTime: '3 min', questionCount: 10,
},
{
    id: 'employee-recognition',
    name: 'Employee Recognition Survey',
    description: 'Recognition frequency, fairness, preferred formats, and programme effectiveness.',
    category: 'hr', categoryLabel: 'HR & Culture', pollType: 'survey',
    icon: '🏆', gradient: 'from-yellow-400 to-amber-500', accentColor: '#eab308',
    question: 'How often do you receive recognition for good work from your manager?',
    options: ['Recognition frequency', 'Manager recognition', 'Peer recognition', 'Fairness', 'Meaningful quality', 'Impact on motivation', 'Preferred format', 'Programme effectiveness', 'Open feedback'],
    suggestedTheme: 'sunset', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'confetti' }, bestFor: ['HR', 'People ops', 'Culture teams'],
    estimatedTime: '3 min', questionCount: 9,
},
{
    id: 'canteen-food-service',
    name: 'Canteen and Food Service Survey',
    description: 'Food quality, variety, dietary options, service speed, cleanliness, and value.',
    category: 'hr', categoryLabel: 'HR & Culture', pollType: 'survey',
    icon: '🍽️', gradient: 'from-orange-400 to-amber-500', accentColor: '#fb923c',
    question: 'How would you rate the overall quality of the food served in our canteen?',
    options: ['Food quality', 'Menu variety', 'Dietary and allergen options', 'Service speed', 'Staff friendliness', 'Cleanliness', 'Value for money', 'NPS', 'Open feedback'],
    suggestedTheme: 'sunset', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'waves' }, bestFor: ['Office catering', 'Facilities management', 'HR teams'],
    estimatedTime: '2 min', questionCount: 9,
},
{
    id: 'employee-mental-health-survey',
    name: 'Employee Mental Health Survey',
    description: 'Psychological safety, stress, manager support, and access to mental health resources.',
    category: 'hr', categoryLabel: 'HR & Culture', pollType: 'survey',
    icon: '🧠', gradient: 'from-teal-500 to-cyan-600', accentColor: '#0891b2',
    question: 'How supported do you feel in maintaining good mental health at work?',
    options: ['Current wellbeing', 'Stress levels', 'Workload impact', 'Psychological safety', 'Manager support quality', 'Resources awareness', 'Resources sufficiency', 'Vs last year', 'Open feedback'],
    suggestedTheme: 'ocean', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'dots' }, bestFor: ['HR', 'People ops', 'Wellbeing leads'],
    estimatedTime: '3 min', questionCount: 9,
    badge: 'Anonymous', badgeColor: 'bg-teal-100 text-teal-700',
},

// ── EVENTS (missing) ──────────────────────────────────────────────
{
    id: 'speaker-evaluation-survey',
    name: 'Speaker Evaluation Survey',
    description: 'Content quality, delivery, engagement, and overall speaker performance.',
    category: 'events', categoryLabel: 'Events & Planning', pollType: 'survey',
    icon: '🎤', gradient: 'from-indigo-500 to-violet-600', accentColor: '#6366f1',
    question: 'How relevant and valuable was the content of this session to you?',
    options: ['Content relevance', 'Content depth', 'Learning value', 'Delivery style', 'Engagement', 'Time management', 'Would recommend speaker', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'grid' }, bestFor: ['Conferences', 'Workshops', 'Corporate events'],
    estimatedTime: '2 min', questionCount: 8,
},
{
    id: 'conference-feedback',
    name: 'Conference Feedback Survey',
    description: 'Overall experience, content quality, networking, venue, value, and return intent.',
    category: 'events', categoryLabel: 'Events & Planning', pollType: 'survey',
    icon: '🏛️', gradient: 'from-slate-600 to-gray-700', accentColor: '#475569',
    question: 'How would you rate the overall conference experience?',
    options: ['Overall experience', 'Content quality', 'Speaker quality', 'Networking value', 'Venue and logistics', 'Value for ticket price', 'Return intent', 'NPS', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'grid' }, bestFor: ['Conference organisers', 'Event teams', 'Associations'],
    estimatedTime: '3 min', questionCount: 9,
},

// ── HEALTHCARE (missing) ──────────────────────────────────────────
{
    id: 'patient-satisfaction',
    name: 'Patient Satisfaction Survey',
    description: 'Appointment access, waiting time, clinical care, communication, and NPS.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '🏥', gradient: 'from-blue-500 to-cyan-600', accentColor: '#0891b2',
    question: 'How satisfied are you with the care you received during your appointment?',
    options: ['Appointment booking', 'Waiting time', 'Receptionist experience', 'Clinical care quality', 'Communication clarity', 'Listened to', 'Overall visit satisfaction', 'NPS', 'Open feedback'],
    suggestedTheme: 'ocean', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'dots' }, bestFor: ['GP practices', 'Clinics', 'Hospitals'],
    estimatedTime: '3 min', questionCount: 10,
},
{
    id: 'dental-satisfaction',
    name: 'Dental Patient Satisfaction Survey',
    description: 'Appointment ease, wait time, clinical quality, pain management, and rebooking intent.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '🦷', gradient: 'from-sky-400 to-blue-500', accentColor: '#0284c7',
    question: 'How easy was it to book your appointment?',
    options: ['Booking ease', 'Wait time', 'Reception welcome', 'Clinical care quality', 'Pain management', 'Treatment explanation', 'Value for money', 'NPS', 'Open feedback'],
    suggestedTheme: 'ocean', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'waves' }, bestFor: ['Dental practices', 'Orthodontists', 'Dental groups'],
    estimatedTime: '2 min', questionCount: 9,
},
{
    id: 'patient-discharge',
    name: 'Patient Discharge Survey',
    description: 'Discharge instructions clarity, follow-up arrangements, and care quality.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '📋', gradient: 'from-teal-500 to-emerald-600', accentColor: '#059669',
    question: 'How clearly were your discharge instructions and next steps explained to you?',
    options: ['Discharge instructions clarity', 'Medication instructions', 'Warning signs explained', 'Follow-up arrangements', 'GP communication', 'Overall inpatient care', 'Staff kindness', 'NPS', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'dots' }, bestFor: ['Hospitals', 'Wards', 'Discharge teams'],
    estimatedTime: '2 min', questionCount: 9,
},

// ── HOSPITALITY (missing) ─────────────────────────────────────────
{
    id: 'hotel-guest-satisfaction',
    name: 'Hotel Guest Satisfaction Survey',
    description: 'Check-in, room quality, dining, facilities, service, and return intent.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '🏨', gradient: 'from-amber-500 to-orange-600', accentColor: '#d97706',
    question: 'How smooth and welcoming was your check-in experience?',
    options: ['Check-in experience', 'Room quality', 'Room cleanliness', 'Bed and sleep quality', 'Bathroom quality', 'Dining quality', 'Food and beverage rating', 'Overall satisfaction', 'NPS', 'Open feedback'],
    suggestedTheme: 'sunset', settings: { anonymousMode: false },
    previewStyle: { bgPattern: 'grid' }, bestFor: ['Hotels', 'B&Bs', 'Serviced apartments'],
    estimatedTime: '3 min', questionCount: 10,
},

// ── MARKETING (missing) ───────────────────────────────────────────
{
    id: 'brand-awareness',
    name: 'Brand Awareness Survey',
    description: 'Brand recall, perception, associations, advocacy, and discovery channel.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '🎯', gradient: 'from-rose-500 to-pink-600', accentColor: '#e11d48',
    question: 'Have you heard of our brand before today?',
    options: ['Brand recall', 'Discovery channel', 'Competitor awareness', 'Association words', 'Brand perception', 'Trust level', 'NPS', 'Discovery source', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'dots' }, bestFor: ['Marketing teams', 'Brand managers', 'Agencies'],
    estimatedTime: '3 min', questionCount: 9,
},

// ── MEMBERSHIP (missing) ──────────────────────────────────────────
{
    id: 'membership-satisfaction',
    name: 'Membership Satisfaction Survey',
    description: 'Member experience, benefits value, events, community, and renewal intent.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '🏅', gradient: 'from-indigo-500 to-blue-600', accentColor: '#4f46e5',
    question: 'Overall, how satisfied are you with your membership?',
    options: ['Overall satisfaction', 'Benefits quality', 'Exclusive content or access', 'Events and programming', 'Community value', 'Staff responsiveness', 'Value for money', 'Renewal intent', 'NPS', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'grid' }, bestFor: ['Membership organisations', 'Clubs', 'Professional bodies'],
    estimatedTime: '3 min', questionCount: 9,
},

// ── PROCUREMENT (missing) ─────────────────────────────────────────
{
    id: 'vendor-evaluation',
    name: 'Vendor Evaluation Survey',
    description: 'Supplier performance, delivery quality, communication, and contract compliance.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '📋', gradient: 'from-slate-500 to-gray-600', accentColor: '#64748b',
    question: 'How satisfied are you with the quality of goods or services delivered by this vendor?',
    options: ['Delivery quality', 'On-time performance', 'Communication quality', 'Issue resolution', 'Contract compliance', 'Value for money', 'Overall relationship', 'NPS', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: false },
    previewStyle: { bgPattern: 'grid' }, bestFor: ['Procurement teams', 'Operations', 'Finance'],
    estimatedTime: '3 min', questionCount: 9,
},

// ── PRODUCT / DIGITAL (missing) ───────────────────────────────────
{
    id: 'product-market-fit',
    name: 'Product Market Fit Survey',
    description: 'The Sean Ellis PMF test — disappointment score, main benefit, and ideal user profile.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '🎯', gradient: 'from-violet-600 to-purple-700', accentColor: '#7c3aed',
    question: 'How would you feel if you could no longer use this product?',
    options: ['Disappointment score', 'Primary benefit', 'Main user type', 'Improvement priority', 'Alternative if gone', 'Recommend likelihood', 'Usage frequency', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'dots' }, bestFor: ['Founders', 'Product teams', 'Early-stage startups'],
    estimatedTime: '3 min', questionCount: 8,
    badge: 'PMF Test', badgeColor: 'bg-violet-100 text-violet-700',
},
{
    id: 'website-feedback',
    name: 'Website Feedback Survey',
    description: 'Navigation, content clarity, findability, performance, and NPS.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '🌐', gradient: 'from-blue-500 to-indigo-600', accentColor: '#3b82f6',
    question: 'How easy was it to find what you were looking for on our website?',
    options: ['Overall experience', 'Ease of navigation', 'Content clarity', 'Found what needed', 'Design impression', 'Performance speed', 'NPS', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'grid' }, bestFor: ['Web teams', 'UX designers', 'Marketing teams'],
    estimatedTime: '2 min', questionCount: 8,
},
{
    id: 'market-research',
    name: 'Market Research Survey',
    description: 'Category usage, buying criteria, price sensitivity, and decision maker profile.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '🔍', gradient: 'from-emerald-500 to-cyan-600', accentColor: '#0891b2',
    question: 'How often do you currently use tools or services in this category?',
    options: ['Usage frequency', 'Current solution', 'Top buying criteria', 'Pain points', 'Price sensitivity', 'Discovery channel', 'Decision timeline', 'Role seniority', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'dots' }, bestFor: ['Founders', 'Product teams', 'Market researchers'],
    estimatedTime: '4 min', questionCount: 10,
},
{
    id: 'it-support',
    name: 'IT Support Satisfaction Survey',
    description: 'Ticket response time, resolution quality, communication, and first-contact resolution.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '💻', gradient: 'from-slate-500 to-blue-600', accentColor: '#475569',
    question: 'How satisfied are you with the speed of response to your IT support request?',
    options: ['Response speed', 'Resolution quality', 'Communication quality', 'Technical knowledge', 'Ease of raising a ticket', 'First contact resolution', 'Overall satisfaction', 'NPS', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'grid' }, bestFor: ['IT teams', 'Helpdesk managers', 'Internal service teams'],
    estimatedTime: '2 min', questionCount: 8,
},
{
    id: 'app-usability',
    name: 'App Usability Survey',
    description: 'Ease of use, feature satisfaction, performance, UI clarity, and NPS.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '📱', gradient: 'from-fuchsia-500 to-pink-600', accentColor: '#c026d3',
    question: 'How easy is it to complete your main tasks in our app?',
    options: ['Task completion ease', 'Top valued feature', 'Feature satisfaction', 'Performance speed', 'UI clarity', 'Error or bug frequency', 'Overall satisfaction', 'NPS', 'Most needed improvement', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'waves' }, bestFor: ['Product teams', 'UX researchers', 'Mobile apps'],
    estimatedTime: '3 min', questionCount: 10,
},
{
    id: 'software-onboarding',
    name: 'Software Onboarding Survey',
    description: 'Setup ease, time to first value, support quality, and confidence after onboarding.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '🚀', gradient: 'from-cyan-500 to-blue-600', accentColor: '#06b6d4',
    question: 'How easy was it to get started and set up the product?',
    options: ['Setup ease', 'Time to first value', 'Setup guidance quality', 'Support responsiveness', 'Feature understanding', 'Confidence post-onboarding', 'Onboarding vs expectations', 'NPS', 'Open feedback'],
    suggestedTheme: 'ocean', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'dots' }, bestFor: ['SaaS teams', 'Customer success', 'Onboarding specialists'],
    estimatedTime: '2 min', questionCount: 9,
},

// ── PROPERTY (missing) ────────────────────────────────────────────
{
    id: 'tenant-satisfaction',
    name: 'Tenant Satisfaction Survey',
    description: 'Property condition, maintenance speed, communication, safety, and renewal intent.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '🏠', gradient: 'from-green-500 to-emerald-600', accentColor: '#16a34a',
    question: 'How satisfied are you with your home or property overall?',
    options: ['Overall property satisfaction', 'Maintenance quality', 'Maintenance response speed', 'Management communication', 'Safety', 'Communal areas', 'Value for money', 'Renewal intent', 'Open feedback'],
    suggestedTheme: 'forest', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'dots' }, bestFor: ['Landlords', 'Property managers', 'Housing associations'],
    estimatedTime: '2 min', questionCount: 9,
},
{
    id: 'vacation-rental-guest-survey',
    name: 'Vacation Rental Guest Survey',
    description: 'Listing accuracy, check-in, cleanliness, amenities, host communication, and NPS.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '🏡', gradient: 'from-teal-500 to-cyan-600', accentColor: '#14b8a6',
    question: 'How accurately did the listing description and photos represent the property?',
    options: ['Listing accuracy', 'Check-in ease', 'Cleanliness', 'Amenities', 'Host responsiveness', 'Location', 'Value for money', 'NPS', 'Open feedback'],
    suggestedTheme: 'ocean', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'waves' }, bestFor: ['Airbnb hosts', 'Holiday let managers', 'Short-term rentals'],
    estimatedTime: '2 min', questionCount: 9,
},
{
    id: 'hoa-resident-survey',
    name: 'HOA Resident Survey',
    description: 'Maintenance, amenities, communication, responsiveness, safety, dues value, and NPS.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '🏘️', gradient: 'from-green-600 to-teal-700', accentColor: '#16a34a',
    question: 'Overall, how satisfied are you as a resident of our community?',
    options: ['Overall satisfaction', 'Shared space maintenance', 'Amenities quality', 'HOA communication', 'Management responsiveness', 'Community safety', 'Dues value', 'NPS', 'Open feedback'],
    suggestedTheme: 'forest', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'grid' }, bestFor: ['HOA boards', 'Condo associations', 'Property managers'],
    estimatedTime: '2 min', questionCount: 9,
},
{
    id: 'student-housing-survey',
    name: 'Student Housing Survey',
    description: 'Room quality, internet, communal areas, maintenance, safety, and value for rent.',
    category: 'education', categoryLabel: 'Education', pollType: 'survey',
    icon: '🎓', gradient: 'from-blue-500 to-indigo-600', accentColor: '#3b82f6',
    question: 'How satisfied are you with the overall quality and condition of your room?',
    options: ['Room quality', 'Internet reliability', 'Communal spaces', 'Maintenance speed', 'Staff helpfulness', 'Safety', 'Value for rent', 'NPS', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'dots' }, bestFor: ['University accommodation', 'Student housing providers', 'Purpose-built student accommodation'],
    estimatedTime: '2 min', questionCount: 9,
},

{
    id: 'museum-visitor-survey',
    name: 'Museum Visitor Survey',
    description: 'Exhibition quality, signage, staff helpfulness, facilities, value, and NPS.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '🏛️', gradient: 'from-stone-500 to-amber-600', accentColor: '#78716c',
    question: 'How satisfied are you with your overall visit today?',
    options: ['Overall visit', 'Exhibition quality', 'Signage and navigation', 'Staff helpfulness', 'Facilities', 'Value for entry price', 'Return intent', 'NPS', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'grid' }, bestFor: ['Museums', 'Galleries', 'Heritage sites'],
    estimatedTime: '2 min', questionCount: 9,
},
{
    id: 'new-hire-30-60-90-survey',
    name: 'New Hire 30-60-90 Day Survey',
    description: 'Onboarding clarity, role confidence, culture fit, and manager support at 30, 60, and 90 days.',
    category: 'hr', categoryLabel: 'HR & Culture', pollType: 'survey',
    icon: '📅', gradient: 'from-indigo-500 to-blue-600', accentColor: '#4f46e5',
    question: 'How clear are you on your role, responsibilities, and what success looks like?',
    options: ['Role clarity', 'Onboarding quality', 'Training quality', 'Manager support', 'Team welcome', 'Tools and access', 'Culture fit', 'Confidence level', 'NPS', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'dots' }, bestFor: ['HR teams', 'People ops', 'Hiring managers'],
    estimatedTime: '3 min', questionCount: 10,
    badge: 'Anonymous', badgeColor: 'bg-indigo-100 text-indigo-700',
},
{
    id: 'podcast-content-survey',
    name: 'Podcast Content Survey',
    description: 'Episode quality, topic preferences, guest feedback, format, and listener NPS.',
    category: 'survey', categoryLabel: 'Surveys & Feedback', pollType: 'survey',
    icon: '🎙️', gradient: 'from-purple-500 to-indigo-600', accentColor: '#7c3aed',
    question: 'How would you rate the overall quality of this podcast?',
    options: ['Overall quality', 'Topic relevance', 'Host delivery', 'Guest quality', 'Episode length', 'Format preference', 'Discovery channel', 'NPS', 'Open feedback'],
    suggestedTheme: 'minimal', settings: { anonymousMode: true },
    previewStyle: { bgPattern: 'waves' }, bestFor: ['Podcast creators', 'Content teams', 'Media producers'],
    estimatedTime: '2 min', questionCount: 9,
},

    // =========================================================================
    // TEAM DECISIONS (10 templates)
    // =========================================================================
    {
        id: 'team-offsite',
        name: 'Team Offsite Location',
        description: 'Let your team vote on the perfect offsite destination with photos',
        category: 'team',
        categoryLabel: 'Team Decisions',
        pollType: 'image',
        icon: '🏝️',
        gradient: 'from-cyan-500 to-blue-600',
        accentColor: '#0891b2',
        question: 'Where should we hold our team offsite?',
        options: [
            'Mountain Lodge Retreat',
            'Beachfront Resort',
            'Urban Conference Center',
            'Countryside Vineyard'
        ],
        suggestedTheme: 'ocean',
        settings: { allowMultiple: false },
        previewStyle: { bgPattern: 'dots' },
        bestFor: ['Team retreats', 'Company offsites', 'Planning committees'],
        estimatedTime: '2 min to create'
    },
    {
        id: 'sprint-priority',
        name: 'Sprint Priority',
        description: 'Rank features or tasks to align on what matters most',
        category: 'team',
        categoryLabel: 'Team Decisions',
        pollType: 'ranked',
        icon: '🎯',
        gradient: 'from-violet-500 to-purple-600',
        accentColor: '#7c3aed',
        question: 'Rank these features by priority for next sprint',
        options: [
            'User authentication improvements',
            'Dashboard analytics',
            'Mobile responsiveness',
            'Performance optimization',
            'New onboarding flow'
        ],
        suggestedTheme: 'minimal',
        settings: { hideResults: false },
        previewStyle: { bgPattern: 'grid' },
        bestFor: ['Sprint planning', 'Product teams', 'Agile ceremonies'],
        estimatedTime: '1 min to create'
    },
    {
        id: 'team-lunch',
        name: 'Team Lunch Vote',
        description: 'Quick poll to decide where the team should eat',
        category: 'team',
        categoryLabel: 'Team Decisions',
        pollType: 'multiple',
        icon: '🍕',
        gradient: 'from-orange-500 to-red-500',
        accentColor: '#ea580c',
        question: 'Where should we go for team lunch?',
        options: [
            '🍕 Pizza Palace',
            '🍔 Burger Barn',
            '🍣 Sushi Station',
            '🥗 Salad Garden',
            '🌮 Taco Town'
        ],
        suggestedTheme: 'sunset',
        settings: { allowMultiple: false },
        previewStyle: { bgPattern: 'waves' },
        bestFor: ['Daily lunch decisions', 'Team outings', 'Office events'],
        estimatedTime: '30 sec to create'
    },
    {
        id: 'feature-ranking',
        name: 'Feature Ranking',
        description: 'Get team consensus on feature priorities with ranked voting',
        category: 'team',
        categoryLabel: 'Team Decisions',
        pollType: 'ranked',
        icon: '📊',
        gradient: 'from-emerald-500 to-teal-600',
        accentColor: '#059669',
        question: 'Rank these product features by importance',
        options: [
            'Dark mode',
            'Export to PDF',
            'Team collaboration',
            'API access',
            'Custom branding'
        ],
        suggestedTheme: 'forest',
        settings: { hideResults: false },
        previewStyle: { bgPattern: 'dots' },
        bestFor: ['Product roadmap', 'Feature prioritization', 'Customer feedback'],
        estimatedTime: '1 min to create'
    },
    {
        id: 'budget-allocation',
        name: 'Budget Allocation',
        description: 'Prioritize where to invest team resources',
        category: 'team',
        categoryLabel: 'Team Decisions',
        pollType: 'ranked',
        icon: '💰',
        gradient: 'from-amber-500 to-yellow-500',
        accentColor: '#d97706',
        question: 'Rank these initiatives by budget priority',
        options: [
            'Marketing campaigns',
            'Product development',
            'Team training',
            'Infrastructure upgrades',
            'Customer support tools'
        ],
        suggestedTheme: 'minimal',
        settings: { hideResults: false },
        previewStyle: { bgPattern: 'grid' },
        bestFor: ['Budget planning', 'Resource allocation', 'Leadership decisions'],
        estimatedTime: '1 min to create'
    },
    {
        id: 'project-name',
        name: 'Project Name Vote',
        description: 'Let the team pick the perfect project codename',
        category: 'team',
        categoryLabel: 'Team Decisions',
        pollType: 'multiple',
        icon: '🚀',
        gradient: 'from-indigo-500 to-blue-600',
        accentColor: '#4f46e5',
        question: 'What should we name our new project?',
        options: [
            'Project Phoenix',
            'Operation Thunder',
            'Initiative Nova',
            'Mission Horizon'
        ],
        suggestedTheme: 'minimal',
        settings: { allowMultiple: false },
        previewStyle: { bgPattern: 'dots' },
        bestFor: ['New projects', 'Product launches', 'Team branding'],
        estimatedTime: '30 sec to create'
    },
    {
        id: 'meeting-time',
        name: 'Find Meeting Time',
        description: 'Discover when everyone is available to meet',
        category: 'team',
        categoryLabel: 'Team Decisions',
        pollType: 'meeting',
        icon: '🗓️',
        gradient: 'from-sky-500 to-blue-600',
        accentColor: '#0284c7',
        question: 'When can you attend the team sync?',
        options: [
            'Monday 10:00 AM',
            'Tuesday 2:00 PM',
            'Wednesday 11:00 AM',
            'Thursday 3:00 PM',
            'Friday 9:00 AM'
        ],
        suggestedTheme: 'minimal',
        settings: { allowMultiple: true },
        previewStyle: { bgPattern: 'grid' },
        bestFor: ['Team meetings', 'Scheduling', 'Availability checks'],
        estimatedTime: '1 min to create'
    },
    {
        id: 'logo-feedback',
        name: 'Logo Design Vote',
        description: 'Get visual feedback on logo concepts',
        category: 'team',
        categoryLabel: 'Team Decisions',
        pollType: 'image',
        icon: '🎨',
        gradient: 'from-pink-500 to-rose-600',
        accentColor: '#e11d48',
        question: 'Which logo design do you prefer?',
        options: [
            'Design A - Modern',
            'Design B - Classic',
            'Design C - Playful',
            'Design D - Minimal'
        ],
        suggestedTheme: 'minimal',
        settings: { allowMultiple: false },
        previewStyle: { bgPattern: 'dots' },
        bestFor: ['Branding decisions', 'Design reviews', 'Creative teams'],
        estimatedTime: '2 min to create'
    },
    {
        id: 'tool-selection',
        name: 'Tool Selection',
        description: 'Compare and vote on new tools for the team',
        category: 'team',
        categoryLabel: 'Team Decisions',
        pollType: 'pairwise',
        icon: '🛠️',
        gradient: 'from-slate-600 to-gray-700',
        accentColor: '#475569',
        question: 'Which project management tool should we use?',
        options: [
            'Notion',
            'Linear',
            'Asana',
            'Monday.com'
        ],
        suggestedTheme: 'dark',
        settings: {},
        previewStyle: { bgPattern: 'grid' },
        bestFor: ['Software decisions', 'Vendor selection', 'Tool evaluation'],
        estimatedTime: '1 min to create'
    },
    {
        id: 'office-policy',
        name: 'Office Policy Vote',
        description: 'Get team input on workplace policies',
        category: 'team',
        categoryLabel: 'Team Decisions',
        pollType: 'multiple',
        icon: '🏢',
        gradient: 'from-teal-500 to-emerald-600',
        accentColor: '#14b8a6',
        question: 'What\'s your preferred work arrangement?',
        options: [
            '🏠 Fully remote',
            '🏢 Fully in-office',
            '🔄 Hybrid (3 days office)',
            '🔄 Hybrid (2 days office)',
            '🤷 Flexible - no set days'
        ],
        suggestedTheme: 'minimal',
        settings: { allowMultiple: false },
        previewStyle: { bgPattern: 'dots' },
        bestFor: ['HR decisions', 'Policy changes', 'Employee input'],
        estimatedTime: '30 sec to create'
    },

    // =========================================================================
    // EVENTS & PLANNING (8 templates)
    // =========================================================================
    {
        id: 'wedding-rsvp',
        name: 'Wedding RSVP',
        description: 'Beautiful wedding invitation response form',
        category: 'events',
        categoryLabel: 'Events & Planning',
        pollType: 'rsvp',
        icon: '💒',
        gradient: 'from-rose-400 to-pink-500',
        accentColor: '#f43f5e',
        question: 'Will you be joining us for our special day?',
        options: [
            'Joyfully Accept',
            'Regretfully Decline'
        ],
        suggestedTheme: 'rose',
        settings: {},
        previewStyle: { bgPattern: 'confetti' },
        bestFor: ['Weddings', 'Engagement parties', 'Rehearsal dinners'],
        estimatedTime: '2 min to create'
    },
    {
        id: 'party-planning',
        name: 'Party Date Poll',
        description: 'Find the best date for your celebration',
        category: 'events',
        categoryLabel: 'Events & Planning',
        pollType: 'meeting',
        icon: '🎉',
        gradient: 'from-fuchsia-500 to-purple-600',
        accentColor: '#c026d3',
        question: 'Which date works best for the party?',
        options: [
            'Saturday, March 15',
            'Saturday, March 22',
            'Saturday, March 29',
            'Saturday, April 5'
        ],
        suggestedTheme: 'neon',
        settings: { allowMultiple: true },
        previewStyle: { bgPattern: 'confetti' },
        bestFor: ['Birthday parties', 'Celebrations', 'Social gatherings'],
        estimatedTime: '1 min to create'
    },
    {
        id: 'potluck-signup',
        name: 'Potluck Signup',
        description: 'Coordinate who brings what to the potluck',
        category: 'events',
        categoryLabel: 'Events & Planning',
        pollType: 'multiple',
        icon: '🍲',
        gradient: 'from-orange-400 to-amber-500',
        accentColor: '#fb923c',
        question: 'What will you bring to the potluck?',
        options: [
            '🥗 Salad / Side dish',
            '🍖 Main course',
            '🍰 Dessert',
            '🥤 Drinks',
            '🍞 Bread / Appetizer'
        ],
        suggestedTheme: 'sunset',
        settings: { allowMultiple: false },
        previewStyle: { bgPattern: 'waves' },
        bestFor: ['Office potlucks', 'Family gatherings', 'Community events'],
        estimatedTime: '30 sec to create'
    },
    {
        id: 'baby-shower',
        name: 'Baby Shower RSVP',
        description: 'Adorable baby shower response form',
        category: 'events',
        categoryLabel: 'Events & Planning',
        pollType: 'rsvp',
        icon: '👶',
        gradient: 'from-sky-400 to-blue-500',
        accentColor: '#38bdf8',
        question: 'Can you join us to celebrate the baby?',
        options: [
            'Yes, I\'ll be there! 🎉',
            'Sorry, I can\'t make it 😢'
        ],
        suggestedTheme: 'ocean',
        settings: {},
        previewStyle: { bgPattern: 'dots' },
        bestFor: ['Baby showers', 'Gender reveals', 'Sip and see'],
        estimatedTime: '2 min to create'
    },
    {
        id: 'reunion-planning',
        name: 'Reunion Planning',
        description: 'Coordinate family or class reunion details',
        category: 'events',
        categoryLabel: 'Events & Planning',
        pollType: 'meeting',
        icon: '👨‍👩‍👧‍👦',
        gradient: 'from-emerald-500 to-green-600',
        accentColor: '#10b981',
        question: 'When can you attend the reunion?',
        options: [
            'July 4th Weekend',
            'Labor Day Weekend',
            'Thanksgiving Weekend',
            'Christmas Week'
        ],
        suggestedTheme: 'forest',
        settings: { allowMultiple: true },
        previewStyle: { bgPattern: 'dots' },
        bestFor: ['Family reunions', 'Class reunions', 'Friend groups'],
        estimatedTime: '1 min to create'
    },
    {
        id: 'activity-vote',
        name: 'Group Activity Vote',
        description: 'Decide on a fun activity for the group',
        category: 'events',
        categoryLabel: 'Events & Planning',
        pollType: 'ranked',
        icon: '🎳',
        gradient: 'from-lime-500 to-green-600',
        accentColor: '#84cc16',
        question: 'Rank your preferred group activities',
        options: [
            '🎳 Bowling',
            '🧗 Rock climbing',
            '🎮 Arcade / Gaming',
            '🍳 Cooking class',
            '🚣 Kayaking'
        ],
        suggestedTheme: 'forest',
        settings: {},
        previewStyle: { bgPattern: 'waves' },
        bestFor: ['Team outings', 'Friend groups', 'Corporate events'],
        estimatedTime: '1 min to create'
    },
    {
        id: 'holiday-party',
        name: 'Holiday Party Poll',
        description: 'Plan the perfect holiday celebration',
        category: 'events',
        categoryLabel: 'Events & Planning',
        pollType: 'multiple',
        icon: '🎄',
        gradient: 'from-red-500 to-green-600',
        accentColor: '#dc2626',
        question: 'What type of holiday party would you prefer?',
        options: [
            '🍽️ Formal dinner',
            '🎉 Casual cocktail party',
            '🏠 Potluck style',
            '🎮 Game night theme',
            '🎭 Costume / Ugly sweater'
        ],
        suggestedTheme: 'sunset',
        settings: { allowMultiple: false },
        previewStyle: { bgPattern: 'confetti' },
        bestFor: ['Office parties', 'Family holidays', 'Friend groups'],
        estimatedTime: '30 sec to create'
    },
    {
        id: 'graduation-party',
        name: 'Graduation Party RSVP',
        description: 'Celebrate academic achievements in style',
        category: 'events',
        categoryLabel: 'Events & Planning',
        pollType: 'rsvp',
        icon: '🎓',
        gradient: 'from-indigo-500 to-purple-600',
        accentColor: '#6366f1',
        question: 'Join us to celebrate this milestone!',
        options: [
            'Count me in! 🎉',
            'Can\'t make it 😔'
        ],
        suggestedTheme: 'minimal',
        settings: {},
        previewStyle: { bgPattern: 'confetti' },
        bestFor: ['High school graduation', 'College graduation', 'Achievement celebrations'],
        estimatedTime: '2 min to create'
    },

    // =========================================================================
    // FEEDBACK (6 templates)
    // =========================================================================
    {
        id: 'product-feedback',
        name: 'Product Feedback',
        description: 'Quick pulse check on product features',
        category: 'feedback',
        categoryLabel: 'Feedback',
        pollType: 'rating',
        icon: '💡',
        gradient: 'from-amber-500 to-orange-600',
        accentColor: '#f59e0b',
        question: 'How would you rate our new feature?',
        options: ['1', '2', '3', '4', '5'],
        suggestedTheme: 'sunset',
        settings: {},
        previewStyle: { bgPattern: 'waves' },
        bestFor: ['Product launches', 'Feature feedback', 'Beta testing'],
        estimatedTime: '30 sec to create'
    },
    {
        id: 'service-rating',
        name: 'Service Rating',
        description: 'Measure customer satisfaction with your service',
        category: 'feedback',
        categoryLabel: 'Feedback',
        pollType: 'rating',
        icon: '⭐',
        gradient: 'from-yellow-400 to-amber-500',
        accentColor: '#eab308',
        question: 'How would you rate our service today?',
        options: ['1', '2', '3', '4', '5'],
        suggestedTheme: 'sunset',
        settings: {},
        previewStyle: { bgPattern: 'dots' },
        bestFor: ['Customer support', 'Service businesses', 'Retail'],
        estimatedTime: '20 sec to create'
    },
    {
        id: 'content-feedback',
        name: 'Content Feedback',
        description: 'Get feedback on articles, videos, or content',
        category: 'feedback',
        categoryLabel: 'Feedback',
        pollType: 'multiple',
        icon: '📝',
        gradient: 'from-blue-500 to-indigo-600',
        accentColor: '#3b82f6',
        question: 'Was this content helpful?',
        options: [
            '👍 Yes, very helpful',
            '😐 Somewhat helpful',
            '👎 Not helpful',
            '🤔 I have suggestions'
        ],
        suggestedTheme: 'minimal',
        settings: { allowMultiple: false },
        previewStyle: { bgPattern: 'grid' },
        bestFor: ['Blog posts', 'Documentation', 'Training materials'],
        estimatedTime: '30 sec to create'
    },
    {
        id: 'meeting-feedback',
        name: 'Meeting Feedback',
        description: 'Quick check on meeting effectiveness',
        category: 'feedback',
        categoryLabel: 'Feedback',
        pollType: 'rating',
        icon: '📊',
        gradient: 'from-teal-500 to-cyan-600',
        accentColor: '#14b8a6',
        question: 'How useful was this meeting?',
        options: ['1', '2', '3', '4', '5'],
        suggestedTheme: 'ocean',
        settings: {},
        previewStyle: { bgPattern: 'waves' },
        bestFor: ['Team meetings', 'Workshops', 'All-hands'],
        estimatedTime: '20 sec to create'
    },
    {
        id: 'presentation-feedback',
        name: 'Presentation Feedback',
        description: 'Gather feedback on presentations or talks',
        category: 'feedback',
        categoryLabel: 'Feedback',
        pollType: 'rating',
        icon: '🎤',
        gradient: 'from-rose-500 to-pink-600',
        accentColor: '#f43f5e',
        question: 'How would you rate this presentation?',
        options: ['1', '2', '3', '4', '5'],
        suggestedTheme: 'sunset',
        settings: {},
        previewStyle: { bgPattern: 'confetti' },
        bestFor: ['Conferences', 'Internal presentations', 'Sales pitches'],
        estimatedTime: '20 sec to create'
    },
    {
        id: 'quick-pulse',
        name: 'Quick Pulse Check',
        description: 'Simple thumbs up/down feedback',
        category: 'feedback',
        categoryLabel: 'Feedback',
        pollType: 'multiple',
        icon: '👍',
        gradient: 'from-green-500 to-emerald-600',
        accentColor: '#22c55e',
        question: 'How do you feel about this?',
        options: [
            '👍 Love it!',
            '👎 Not a fan'
        ],
        suggestedTheme: 'forest',
        settings: { allowMultiple: false },
        previewStyle: { bgPattern: 'dots' },
        bestFor: ['Quick decisions', 'Approval voting', 'Simple feedback'],
        estimatedTime: '15 sec to create'
    },

    // =========================================================================
    // HR & CULTURE (6 templates)
    // =========================================================================
    {
        id: 'onboarding-feedback',
        name: 'Onboarding Feedback',
        description: 'Improve new hire experience with feedback',
        category: 'hr',
        categoryLabel: 'HR & Culture',
        pollType: 'rating',
        icon: '🚀',
        gradient: 'from-indigo-500 to-purple-600',
        accentColor: '#6366f1',
        question: 'How would you rate your onboarding experience?',
        options: ['1', '2', '3', '4', '5'],
        suggestedTheme: 'minimal',
        settings: {},
        previewStyle: { bgPattern: 'dots' },
        bestFor: ['New hires', 'HR teams', '30/60/90 day reviews'],
        estimatedTime: '30 sec to create'
    },
    {
        id: 'benefits-survey',
        name: 'Benefits Preferences',
        description: 'Understand what benefits matter most to your team',
        category: 'hr',
        categoryLabel: 'HR & Culture',
        pollType: 'ranked',
        icon: '🎁',
        gradient: 'from-emerald-500 to-teal-600',
        accentColor: '#059669',
        question: 'Rank these benefits by importance to you',
        options: [
            '🏥 Health insurance',
            '🏠 Remote work flexibility',
            '📚 Learning & development',
            '🏋️ Wellness programs',
            '👶 Parental leave'
        ],
        suggestedTheme: 'forest',
        settings: {},
        previewStyle: { bgPattern: 'dots' },
        bestFor: ['Benefits planning', 'HR strategy', 'Employee input'],
        estimatedTime: '1 min to create'
    },
    {
        id: 'culture-values',
        name: 'Culture Values Vote',
        description: 'Align on company values that matter',
        category: 'hr',
        categoryLabel: 'HR & Culture',
        pollType: 'ranked',
        icon: '💎',
        gradient: 'from-violet-500 to-purple-600',
        accentColor: '#8b5cf6',
        question: 'Which values resonate most with you?',
        options: [
            '🤝 Collaboration',
            '💡 Innovation',
            '🎯 Excellence',
            '❤️ Empathy',
            '🔓 Transparency'
        ],
        suggestedTheme: 'minimal',
        settings: {},
        previewStyle: { bgPattern: 'grid' },
        bestFor: ['Culture building', 'Values alignment', 'Leadership'],
        estimatedTime: '1 min to create'
    },
    {
        id: 'team-morale',
        name: 'Team Morale Check',
        description: 'Anonymous pulse on team sentiment',
        category: 'hr',
        categoryLabel: 'HR & Culture',
        pollType: 'multiple',
        icon: '🌡️',
        gradient: 'from-amber-400 to-orange-500',
        accentColor: '#f59e0b',
        question: 'How are you feeling about work this week?',
        options: [
            '🌟 Great - energized!',
            '😊 Good - steady',
            '😐 Okay - manageable',
            '😓 Stressed - need support',
            '😔 Struggling - let\'s talk'
        ],
        suggestedTheme: 'sunset',
        settings: { hideResults: true },
        previewStyle: { bgPattern: 'waves' },
        bestFor: ['Weekly check-ins', 'Team health', 'Manager insights'],
        estimatedTime: '20 sec to create'
    },
    {
        id: 'recognition-poll',
        name: 'Team Recognition',
        description: 'Celebrate team members who went above and beyond',
        category: 'hr',
        categoryLabel: 'HR & Culture',
        pollType: 'multiple',
        icon: '🏆',
        gradient: 'from-yellow-400 to-amber-500',
        accentColor: '#eab308',
        question: 'Who deserves a shoutout this week?',
        options: [
            'Team Member 1',
            'Team Member 2',
            'Team Member 3',
            'Team Member 4',
            'Someone else (comment)'
        ],
        suggestedTheme: 'sunset',
        settings: { allowMultiple: true },
        previewStyle: { bgPattern: 'confetti' },
        bestFor: ['Peer recognition', 'Team meetings', 'Culture building'],
        estimatedTime: '1 min to create'
    },
    {
        id: 'training-interest',
        name: 'Training Interest Survey',
        description: 'Find out what skills your team wants to develop',
        category: 'hr',
        categoryLabel: 'HR & Culture',
        pollType: 'ranked',
        icon: '📚',
        gradient: 'from-blue-500 to-indigo-600',
        accentColor: '#3b82f6',
        question: 'What training would be most valuable?',
        options: [
            '💻 Technical skills',
            '🎤 Public speaking',
            '👥 Leadership',
            '📊 Data analysis',
            '🎨 Design thinking'
        ],
        suggestedTheme: 'minimal',
        settings: {},
        previewStyle: { bgPattern: 'grid' },
        bestFor: ['L&D planning', 'Skill development', 'Career growth'],
        estimatedTime: '1 min to create'
    },

    // =========================================================================
    // EDUCATION (6 templates)
    // =========================================================================
    {
        id: 'class-poll',
        name: 'Classroom Poll',
        description: 'Engage students with interactive polling',
        category: 'education',
        categoryLabel: 'Education',
        pollType: 'multiple',
        icon: '🎓',
        gradient: 'from-blue-500 to-indigo-600',
        accentColor: '#3b82f6',
        question: 'What topic should we cover next?',
        options: [
            'Topic A',
            'Topic B',
            'Topic C',
            'Review previous material'
        ],
        suggestedTheme: 'minimal',
        settings: { allowMultiple: false },
        previewStyle: { bgPattern: 'dots' },
        bestFor: ['Classrooms', 'Workshops', 'Training sessions'],
        estimatedTime: '30 sec to create'
    },
    {
        id: 'assignment-preference',
        name: 'Assignment Preference',
        description: 'Let students choose their preferred assignment format',
        category: 'education',
        categoryLabel: 'Education',
        pollType: 'ranked',
        icon: '📋',
        gradient: 'from-teal-500 to-cyan-600',
        accentColor: '#14b8a6',
        question: 'Rank your preferred assignment formats',
        options: [
            '📝 Written essay',
            '🎥 Video presentation',
            '🖼️ Visual poster',
            '👥 Group project',
            '🎤 Oral presentation'
        ],
        suggestedTheme: 'ocean',
        settings: {},
        previewStyle: { bgPattern: 'waves' },
        bestFor: ['Course design', 'Student engagement', 'Flexible learning'],
        estimatedTime: '1 min to create'
    },
    {
        id: 'study-group',
        name: 'Study Group Time',
        description: 'Find when everyone can meet to study',
        category: 'education',
        categoryLabel: 'Education',
        pollType: 'meeting',
        icon: '📖',
        gradient: 'from-purple-500 to-indigo-600',
        accentColor: '#a855f7',
        question: 'When can you join the study group?',
        options: [
            'Monday evening',
            'Wednesday afternoon',
            'Thursday evening',
            'Saturday morning',
            'Sunday afternoon'
        ],
        suggestedTheme: 'minimal',
        settings: { allowMultiple: true },
        previewStyle: { bgPattern: 'grid' },
        bestFor: ['Study groups', 'Project teams', 'Tutoring sessions'],
        estimatedTime: '1 min to create'
    },
    {
        id: 'field-trip',
        name: 'Field Trip Vote',
        description: 'Let students vote on field trip destinations',
        category: 'education',
        categoryLabel: 'Education',
        pollType: 'image',
        icon: '🚌',
        gradient: 'from-green-500 to-emerald-600',
        accentColor: '#22c55e',
        question: 'Where should we go for our field trip?',
        options: [
            '🏛️ History Museum',
            '🔬 Science Center',
            '🎭 Theater',
            '🌳 Nature Reserve'
        ],
        suggestedTheme: 'forest',
        settings: { allowMultiple: false },
        previewStyle: { bgPattern: 'dots' },
        bestFor: ['School trips', 'Educational outings', 'Class decisions'],
        estimatedTime: '1 min to create'
    },
    {
        id: 'course-feedback',
        name: 'Course Evaluation',
        description: 'Gather student feedback on course content',
        category: 'education',
        categoryLabel: 'Education',
        pollType: 'rating',
        icon: '📊',
        gradient: 'from-amber-500 to-orange-500',
        accentColor: '#f59e0b',
        question: 'How would you rate this course overall?',
        options: ['1', '2', '3', '4', '5'],
        suggestedTheme: 'sunset',
        settings: {},
        previewStyle: { bgPattern: 'waves' },
        bestFor: ['Course evaluations', 'Training feedback', 'Workshops'],
        estimatedTime: '20 sec to create'
    },
    {
        id: 'project-group',
        name: 'Group Project Topic',
        description: 'Let the group decide on a project topic',
        category: 'education',
        categoryLabel: 'Education',
        pollType: 'ranked',
        icon: '🎯',
        gradient: 'from-rose-500 to-pink-600',
        accentColor: '#e11d48',
        question: 'Rank your preferred project topics',
        options: [
            'Topic 1: Research project',
            'Topic 2: Case study',
            'Topic 3: Creative project',
            'Topic 4: Technical build'
        ],
        suggestedTheme: 'minimal',
        settings: {},
        previewStyle: { bgPattern: 'dots' },
        bestFor: ['Group projects', 'Team assignments', 'Collaborative work'],
        estimatedTime: '1 min to create'
    },

    // =========================================================================
    // FUN & SOCIAL (7 templates)
    // =========================================================================
    {
        id: 'this-or-that',
        name: 'This or That',
        description: 'Fun icebreaker to spark conversations',
        category: 'fun',
        categoryLabel: 'Fun & Social',
        pollType: 'pairwise',
        icon: '🎭',
        gradient: 'from-fuchsia-500 to-pink-600',
        accentColor: '#c026d3',
        question: 'This or That: Get to know your team!',
        options: [
            '☕ Coffee',
            '🍵 Tea',
            '🌅 Early bird',
            '🦉 Night owl',
            '📚 Books',
            '🎬 Movies'
        ],
        suggestedTheme: 'neon',
        settings: {},
        previewStyle: { bgPattern: 'confetti' },
        bestFor: ['Icebreakers', 'Team bonding', 'Social events'],
        estimatedTime: '1 min to create'
    },
    {
        id: 'movie-night',
        name: 'Movie Night Pick',
        description: 'Vote on what to watch together',
        category: 'fun',
        categoryLabel: 'Fun & Social',
        pollType: 'image',
        icon: '🎬',
        gradient: 'from-purple-600 to-indigo-700',
        accentColor: '#7c3aed',
        question: 'What movie should we watch for team movie night?',
        options: [
            '🎬 Action thriller',
            '😂 Comedy',
            '🚀 Sci-fi adventure',
            '🎭 Drama'
        ],
        suggestedTheme: 'dark',
        settings: { allowMultiple: false },
        previewStyle: { bgPattern: 'dots' },
        bestFor: ['Team movie nights', 'Watch parties', 'Social events'],
        estimatedTime: '1 min to create'
    },
    {
        id: 'pet-photo-contest',
        name: 'Pet Photo Contest',
        description: 'Vote on the cutest pet photos',
        category: 'fun',
        categoryLabel: 'Fun & Social',
        pollType: 'image',
        icon: '🐾',
        gradient: 'from-amber-400 to-orange-500',
        accentColor: '#f59e0b',
        question: 'Vote for the cutest pet!',
        options: [
            'Pet 1',
            'Pet 2',
            'Pet 3',
            'Pet 4'
        ],
        suggestedTheme: 'sunset',
        settings: { allowMultiple: false },
        previewStyle: { bgPattern: 'confetti' },
        bestFor: ['Fun contests', 'Team bonding', 'Slack channels'],
        estimatedTime: '2 min to create'
    },
    {
        id: 'trivia-answer',
        name: 'Trivia Question',
        description: 'Quick trivia for team fun',
        category: 'fun',
        categoryLabel: 'Fun & Social',
        pollType: 'multiple',
        icon: '🧠',
        gradient: 'from-emerald-500 to-teal-600',
        accentColor: '#14b8a6',
        question: 'Which planet is known as the Red Planet?',
        options: [
            'Venus',
            'Mars',
            'Jupiter',
            'Saturn'
        ],
        suggestedTheme: 'forest',
        settings: { allowMultiple: false, hideResults: true },
        previewStyle: { bgPattern: 'dots' },
        bestFor: ['Trivia nights', 'Team games', 'Icebreakers'],
        estimatedTime: '30 sec to create'
    },
    {
        id: 'bracket-challenge',
        name: 'Bracket Challenge',
        description: 'Tournament-style voting on favorites',
        category: 'fun',
        categoryLabel: 'Fun & Social',
        pollType: 'pairwise',
        icon: '🏅',
        gradient: 'from-yellow-500 to-amber-600',
        accentColor: '#d97706',
        question: 'Best snack bracket: Which wins?',
        options: [
            '🍕 Pizza',
            '🌮 Tacos',
            '🍔 Burgers',
            '🍟 Fries',
            '🍩 Donuts',
            '🍦 Ice cream'
        ],
        suggestedTheme: 'sunset',
        settings: {},
        previewStyle: { bgPattern: 'confetti' },
        bestFor: ['Bracket tournaments', 'Fun debates', 'Team engagement'],
        estimatedTime: '1 min to create'
    },
    {
        id: 'music-friday',
        name: 'Music Friday',
        description: 'Vote on the office playlist',
        category: 'fun',
        categoryLabel: 'Fun & Social',
        pollType: 'ranked',
        icon: '🎵',
        gradient: 'from-pink-500 to-rose-600',
        accentColor: '#e11d48',
        question: 'Rank these genres for Friday\'s playlist',
        options: [
            '🎸 Rock',
            '🎹 Pop',
            '🎷 Jazz',
            '🎻 Classical',
            '🎤 Hip hop'
        ],
        suggestedTheme: 'neon',
        settings: {},
        previewStyle: { bgPattern: 'waves' },
        bestFor: ['Office playlists', 'Music voting', 'Team fun'],
        estimatedTime: '1 min to create'
    },
    {
        id: 'would-you-rather',
        name: 'Would You Rather',
        description: 'Classic fun question for team bonding',
        category: 'fun',
        categoryLabel: 'Fun & Social',
        pollType: 'multiple',
        icon: '🤔',
        gradient: 'from-cyan-500 to-blue-600',
        accentColor: '#0891b2',
        question: 'Would you rather have the ability to fly or be invisible?',
        options: [
            '🦅 Fly anywhere',
            '👻 Be invisible'
        ],
        suggestedTheme: 'ocean',
        settings: { allowMultiple: false },
        previewStyle: { bgPattern: 'waves' },
        bestFor: ['Icebreakers', 'Team bonding', 'Fun discussions'],
        estimatedTime: '20 sec to create'
    },
];

// Helper to get templates by category
export const getTemplatesByCategory = (category: string): PollTemplate[] => {
    if (category === 'all') return POLL_TEMPLATES;
    return POLL_TEMPLATES.filter(t => t.category === category);
};

// Helper to get a template by ID
export const getTemplateById = (id: string): PollTemplate | undefined => {
    return POLL_TEMPLATES.find(t => t.id === id);
};

// Helper to get templates by poll type
export const getTemplatesByPollType = (pollType: string): PollTemplate[] => {
    return POLL_TEMPLATES.filter(t => t.pollType === pollType);
};

// Helper to get featured templates (for homepage)
export const getFeaturedTemplates = (): PollTemplate[] => {
    return POLL_TEMPLATES.filter(t => t.featured);
};

// Helper to get survey templates
export const getSurveyTemplates = (): PollTemplate[] => {
    return POLL_TEMPLATES.filter(t => t.pollType === 'survey');
};

// Get template count by category
export const getTemplateCounts = (): Record<string, number> => {
    const counts: Record<string, number> = { all: POLL_TEMPLATES.length };
    TEMPLATE_CATEGORIES.forEach(cat => {
        if (cat.id !== 'all') {
            counts[cat.id] = POLL_TEMPLATES.filter(t => t.category === cat.id).length;
        }
    });
    return counts;
};